export interface FixtureFamily {
  id: string;
  name: string;
  category: string;
  type: string;
  discipline: "architectural" | "mechanical" | "electrical" | "plumbing" | "fire";
  size_m: [number, number, number];
  material: string;
  keywords: string[];
  mounting: "floor" | "wall" | "ceiling";
}

export const fixtureFamilies: FixtureFamily[] = [
  {
    id: "dajoong:furniture:workstation-single",
    name: "Single workstation",
    category: "Furniture",
    type: "workstation",
    discipline: "architectural",
    size_m: [1.5, 0.75, 0.76],
    material: "oak and powder coated steel",
    keywords: ["desk", "office", "table"],
    mounting: "floor",
  },
  {
    id: "dajoong:furniture:conference-table-8",
    name: "Conference table, 8 seats",
    category: "Furniture",
    type: "conference-table",
    discipline: "architectural",
    size_m: [2.7, 1.1, 0.76],
    material: "wood veneer",
    keywords: ["meeting", "boardroom", "table"],
    mounting: "floor",
  },
  {
    id: "dajoong:casework:base-cabinet-900",
    name: "Base cabinet, 900 mm",
    category: "Casework",
    type: "casework",
    discipline: "architectural",
    size_m: [0.9, 0.62, 0.9],
    material: "laminate",
    keywords: ["cabinet", "kitchen", "storage"],
    mounting: "floor",
  },
  {
    id: "dajoong:plumbing:toilet-floor-mounted",
    name: "Floor mounted toilet",
    category: "Plumbing fixtures",
    type: "toilet",
    discipline: "plumbing",
    size_m: [0.4, 0.7, 0.78],
    material: "vitreous china",
    keywords: ["wc", "bathroom", "lavatory"],
    mounting: "floor",
  },
  {
    id: "dajoong:plumbing:lavatory-wall-mounted",
    name: "Wall mounted lavatory",
    category: "Plumbing fixtures",
    type: "sink",
    discipline: "plumbing",
    size_m: [0.58, 0.48, 0.85],
    material: "vitreous china",
    keywords: ["sink", "basin", "bathroom"],
    mounting: "wall",
  },
  {
    id: "dajoong:plumbing:service-sink",
    name: "Service sink",
    category: "Plumbing fixtures",
    type: "sink",
    discipline: "plumbing",
    size_m: [0.65, 0.6, 0.62],
    material: "stainless steel",
    keywords: ["janitor", "mop", "utility"],
    mounting: "floor",
  },
  {
    id: "dajoong:mechanical:fan-coil-compact",
    name: "Compact fan coil unit",
    category: "Mechanical equipment",
    type: "fan-coil",
    discipline: "mechanical",
    size_m: [1.1, 0.55, 0.35],
    material: "galvanized steel",
    keywords: ["hvac", "fcu", "air"],
    mounting: "wall",
  },
  {
    id: "dajoong:mechanical:ceiling-diffuser-600",
    name: "Ceiling diffuser, 600 mm",
    category: "Mechanical equipment",
    type: "ceiling-diffuser",
    discipline: "mechanical",
    size_m: [0.6, 0.6, 0.08],
    material: "powder coated aluminum",
    keywords: ["hvac", "supply", "air", "ceiling"],
    mounting: "ceiling",
  },
  {
    id: "dajoong:electrical:panelboard-recessed",
    name: "Recessed panelboard",
    category: "Electrical equipment",
    type: "electrical-panel",
    discipline: "electrical",
    size_m: [0.55, 0.18, 1.1],
    material: "painted steel",
    keywords: ["panel", "distribution", "power"],
    mounting: "wall",
  },
  {
    id: "dajoong:electrical:receptacle-duplex",
    name: "Duplex receptacle",
    category: "Electrical equipment",
    type: "receptacle",
    discipline: "electrical",
    size_m: [0.07, 0.04, 0.12],
    material: "thermoplastic",
    keywords: ["outlet", "power", "socket"],
    mounting: "wall",
  },
  {
    id: "dajoong:lighting:linear-pendant-1200",
    name: "Linear pendant, 1200 mm",
    category: "Lighting",
    type: "pendant-light",
    discipline: "electrical",
    size_m: [1.2, 0.08, 0.12],
    material: "anodized aluminum",
    keywords: ["light", "luminaire", "ceiling"],
    mounting: "ceiling",
  },
  {
    id: "dajoong:fire:sprinkler-concealed",
    name: "Concealed sprinkler head",
    category: "Fire protection",
    type: "sprinkler-head",
    discipline: "fire",
    size_m: [0.08, 0.08, 0.05],
    material: "brass and painted cover",
    keywords: ["sprinkler", "fire", "ceiling"],
    mounting: "ceiling",
  },
  {
    id: "dajoong:fire:smoke-detector-addressable",
    name: "Addressable smoke detector",
    category: "Fire protection",
    type: "smoke-detector",
    discipline: "fire",
    size_m: [0.13, 0.13, 0.05],
    material: "white polymer",
    keywords: ["alarm", "smoke", "ceiling"],
    mounting: "ceiling",
  },
];
